package com.hibernate.user;

// default package
// Generated Nov 9, 2013 3:03:20 AM by Hibernate Tools 3.4.0.CR1

/**
 * Bonus generated by hbm2java
 */
public class Bonus implements java.io.Serializable {

	private BonusId id;

	public Bonus() {
	}

	public Bonus(BonusId id) {
		this.id = id;
	}

	public BonusId getId() {
		return this.id;
	}

	public void setId(BonusId id) {
		this.id = id;
	}

}
