package com.hibernate.user;
// default package
// Generated Dec 20, 2013 2:48:31 AM by Hibernate Tools 3.4.0.CR1

/**
 * Ordercategorydetails generated by hbm2java
 */
public class Ordercategorydetails implements java.io.Serializable {

	private OrdercategorydetailsId id;
	private Ordercategorymaster ordercategorymaster;

	public Ordercategorydetails() {
	}

	public Ordercategorydetails(OrdercategorydetailsId id) {
		this.id = id;
	}

	public Ordercategorydetails(OrdercategorydetailsId id,
			Ordercategorymaster ordercategorymaster) {
		this.id = id;
		this.ordercategorymaster = ordercategorymaster;
	}

	public OrdercategorydetailsId getId() {
		return this.id;
	}

	public void setId(OrdercategorydetailsId id) {
		this.id = id;
	}

	public Ordercategorymaster getOrdercategorymaster() {
		return this.ordercategorymaster;
	}

	public void setOrdercategorymaster(Ordercategorymaster ordercategorymaster) {
		this.ordercategorymaster = ordercategorymaster;
	}

}
