package com.hibernate.user;
// default package
// Generated Dec 20, 2013 2:48:31 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * OrdercategorydetailsId generated by hbm2java
 */
public class OrdercategorydetailsId implements java.io.Serializable {

	private BigDecimal categoryid;
	private String name;
	private String ingrediants;
	private BigDecimal price;

	public OrdercategorydetailsId() {
	}

	public OrdercategorydetailsId(BigDecimal categoryid, String name,
			String ingrediants, BigDecimal price) {
		this.categoryid = categoryid;
		this.name = name;
		this.ingrediants = ingrediants;
		this.price = price;
	}

	public BigDecimal getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(BigDecimal categoryid) {
		this.categoryid = categoryid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIngrediants() {
		return this.ingrediants;
	}

	public void setIngrediants(String ingrediants) {
		this.ingrediants = ingrediants;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdercategorydetailsId))
			return false;
		OrdercategorydetailsId castOther = (OrdercategorydetailsId) other;

		return ((this.getCategoryid() == castOther.getCategoryid()) || (this
				.getCategoryid() != null && castOther.getCategoryid() != null && this
				.getCategoryid().equals(castOther.getCategoryid())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getIngrediants() == castOther.getIngrediants()) || (this
						.getIngrediants() != null
						&& castOther.getIngrediants() != null && this
						.getIngrediants().equals(castOther.getIngrediants())))
				&& ((this.getPrice() == castOther.getPrice()) || (this
						.getPrice() != null && castOther.getPrice() != null && this
						.getPrice().equals(castOther.getPrice())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCategoryid() == null ? 0 : this.getCategoryid()
						.hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37
				* result
				+ (getIngrediants() == null ? 0 : this.getIngrediants()
						.hashCode());
		result = 37 * result
				+ (getPrice() == null ? 0 : this.getPrice().hashCode());
		return result;
	}

}
